version: '3.8'

services:
  elasticsearchai:
      image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
      container_name: elasticsearchai
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - ${ES_PORT}:9200
      restart: always
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
        - http.cors.allow-origin="*"
        - http.cors.enabled=true
        - http.cors.allow-credentials=true
        - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
        - http.cors.allow-headers=X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept, x-elastic-client-meta
      ulimits:
        memlock:
          soft: -1
          hard: -1
  kibanaai:
      depends_on:
        - elasticsearchai
      image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
      container_name: kibanaai
      volumes:
        - kibana-data:/usr/share/kibana/data
      ports:
        - ${KIBANA_PORT}:5601
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearchai:9200
  mongo:
    depends_on:
          - kibanaai
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  cache:
    depends_on:
          - mongo
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  api:
    depends_on:
      - cache
    build: ./backend
    image: api
    container_name: api
    # running bin bash script to spin up fastapi and rq worker
    command: ["/bin/bash", "./run_services.sh"]
    ports:
      - 8000:8000
    volumes:
       - ./backend:/api
  frontend:
    depends_on:
      - api
    build: ./frontend
    image: frontend
    container_name: frontend
    command: ["/bin/bash", "./run_services.sh"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    environment:
    # Adding REACT_APP prefix, so that react could pick the ES_index env. var. 
      - REACT_APP_ES_INDEX=${ES_INDEX}
volumes:
  dbdata6:
  cache:
    driver: local
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local